[package]
authors = ["Brandon Matthews <bmatthews@zipcar.com>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "Peripheral access API for STM32L0x1 microcontrollers"
keywords = ["arm", "cortex-m", "stm32l0x1", "hal"]
license = "0BSD"
name = "stm32l0x1-hal"
repository = "https://github.com/thenewwazoo/stm32l0x1-hal/"
version = "0.5.0"

[dependencies]
cortex-m = "0.5"
nb = "0.1"
stm32l0x1 = "0.13"

#bare-metal = "0.2"
#cortex-m-rt = "0.5"
#panic-abort = "0.2"

[dependencies.cast]
default-features = false
version = "0.2.2"

[dependencies.embedded-hal]
version = "0.2"
features = ["unproven"]

[features]
default = ["rt"]
rt = ["stm32l0x1/rt"]

[profile]

[profile.dev]
debug = true
lto = true

[profile.release]
debug = true
lto = true
opt-level = "s"
