[package]
authors = ["Brandon Matthews <bmatthews@zipcar.com>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "Peripheral access API for STM32L0x1 microcontrollers"
keywords = ["arm", "cortex-m", "stm32l0x1", "hal"]
license = "0BSD"
name = "stm32l0x1-hal"
repository = "https://github.com/thenewwazoo/stm32l0x1-hal/"
version = "0.6.4"

[dependencies]
cortex-m = "0.5"
nb = "0.1"
stm32l0x1 = "0.13"

[dependencies.embedded-hal]
version = "0.2"
features = ["unproven"]

[features]
default = ["rt"]
rt = ["stm32l0x1/rt"]
STM32L011x3 = []
STM32L011x4 = []
STM32L031x4 = []
STM32L031x6 = []

# This HAL crate depends on my not-yet-accepted ADC traits
[patch.crates-io.embedded-hal]
git = "https://github.com/thenewwazoo/embedded-hal.git"
branch = "adc"
